apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-smtp-config
  namespace: monitoring-latest
data:
  grafana.ini:
    smtp:
      enabled: true
      host: smtp.gmail.com:587
      from_address: admin@grafana.localhost
      from_name: ParkLoyalty-Grafana
      skip_verify: true
      existingSecret: grafana-smtp-secret
        

    