apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-smtp-config
  namespace: monitoring-latest
data:  
  grafana.ini: |
    [smtp]
    enabled = true
    host = smtp.gmail.com:465
    from_address = admin@grafana.localhost
    from_name = ParkLoyalty-Grafana
    skip_verify = true
    existingSecret = grafana-smtp-secret
    user = techops@urolime.com
    password = UR0AFUUiUnip8S0l1@
    
        

    