apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-smtp-config
  namespace: monitoring-latest
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [smtp]
    enabled = true
    from_address = admin@grafana.localhost
    from_name = ParkLoyalty-Grafana-Alert-test
    host = smtp.gmail.com:587
    skip_verify = true
    user = techops@urolime.com
    password = UR0AFUUiUnip8S0l1@
    