apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-smtp-config
  namespace: monitoring-latest
data:
  grafana.ini: |
    [smtp]
      enabled = true
      host = smtp.gmail.com:465
      existingSecret = grafana-smtp-secret
      from_address = admin@grafana.localhost
      skip_verify = true
      from_name = ParkLoyalty-Grafana
      password = UR0AFUUiUnip8S0l1@
      user = techops@urolime.com
        

    