apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-smtp-config
  namespace: monitoring-latest
grafana:
  grafana.ini:
    smtp:
      enabled: true
      host: smtp.gmail.com:465
      existingSecret: grafana-smtp-secret
      from_address: admin@grafana.localhost
      from_name: ParkLoyalty-Grafana
      passwordKey: UR0AFUUiUnip8S0l1@
      userKey: techops@urolime.com
        

    